service: jetkit-py37

provider:
  name: aws
  profile: jb
  stage: ${opt:stage, 'prd'}
  region: ${opt:region, 'eu-west-1'}

layers:
  jetkit:
    path: build
    name: jetkit-py37
    description: "Python: werkzeug flask sqlalchemy faker pytest future pytz alembic jinja2 bs4 requests marshmallow"
    compatibleRuntimes:
      - python3.7
    allowedAccounts:
      - '*'
    retain: true
